title = "My Thoughts Go Here"
base_url = "https://krruzic.xyz"

highlight_theme = "axar"

compile_sass = false
highlight_code = true
build_search_index = true
generate_rss = true

taxonomies = [
  {name = "tags"}
]
[extra]
